[flare_capa]
enabled = yes
on_demand = no
static = yes
cape = yes
procdump = yes
behavior = yes

[floss]
enabled = yes
on_demand = yes
static_strings = no
stack_strings = yes
decoded_strings = yes
tight_strings = yes
min_length = 5
sigs_path = data/flare-signatures

[die]
enabled = yes
binary = /usr/bin/diec

[trid]
enabled = yes
identifier = data/trid/trid
definitions = data/trid/triddefs.trd
