[basic]
delete_memdump = no
delete_memdump_on_exception = no

[info]
enabled = yes
[pslist]
enabled = yes
[psscan]
enabled = yes
[cmdline]
enabled = yes
[dlllist]
enabled = yes
[handles]
enabled = yes
[getsids]
enabled = yes
[privs]
enabled = yes
[netscan]
enabled = yes
[svcscan]
enabled = yes
[malfind]
enabled = yes
